### ISSUE TITLE
Doesn't seem to know words left and right

### ISSUE THREAD

**Issue by LordZorgoth** [vspinu/company-math#4]
This forces one to not use autocomplete in math mode. If it's on, you can end up with, e.g., \rightarrow) instead of \right).

**Comment by LordZorgoth** [comment]
This forces one to not use autocomplete in math mode. If it's on, you can end up with, e.g., \rightarrow) instead of \right).

**Comment by vspinu** [comment]
`\left` and `\right` are not symbols and including them into [`math-symbol-list`](https://github.com/vspinu/math-symbol-lists) would be wrong. They are already part of [latex list](https://github.com/vspinu/math-symbol-lists/blob/master/math-symbol-lists.el#L3007). 

You can add these symbols to the predefined [symbol lists](https://github.com/vspinu/company-math/blob/master/company-math.el#L92-L96).

**Comment by LordZorgoth** [comment]
The problem is that company-math doesn't understand that these are associated with backslash.

It will complete left, right, mathcal, mathbb, etc.

But it won't complete \left, \right, \mathcal, \mathbb. The issue is not that they aren't on the symbols list. The issue is that company-math doesn't know how to use the command list.

**Comment by LordZorgoth** [comment]
If you type "\lef" and run "company-latex-commands", it doesn't come up with \left. If you type "lef," it does come up with "left." That is clearly not how we want it to behave.

**Comment by vspinu** [comment]
I don't see that. It works only with `\lef` prefix for me, not with `lef`. 

Unfortunately it does not come with \left completion because \left is actually not part of `math-symbol-list-latex-commands` list. But`\right` is. I just noticed that and already fixed in `math-symbol-lists` repo.

**Comment by LordZorgoth** [comment]
Curious. I also see that left isn't on the list and right is. But it is still completing both right _and_ left without backslashes, but neither when I do have backslashes.

This is when running "M-x: company-latex-commands"

**Comment by LordZorgoth** [comment]
Actually, I think the fact that it works on left and right without backslash may be a red herring. It seems to work on miscellaneous words that have nothing to do with LaTeX, so I guess it looks at dabbrev after failing to find a match. But I'm still not matching any latex commands except for symbols when I run "company-latex-commands."

(edit: after experimentation, what I have found is that with the settings I had at the time, you could only be sure of restricting to company-latex-commands completions if you hit Alt-X before dabbrev has time to think)

**Comment by LordZorgoth** [comment]
Ah, so if I set "Company Math Allow Latex Symbols In Faces" to "t", I can complete everything, which solves the serious issue.

Long term, the code should make a distinction between LaTeX commands that only work in math mode, LaTeX commands that only work outside math mode, and LaTeX commands that work in both modes. 

I don't have time to do that right now, but the code looks straightforward enough that I think I could work on it in a month or two.

**Comment by LordZorgoth** [comment]
Actually, now I don't have completions for symbols. It seems like I can only have one or the other, which is of course rather suboptimal. Is there some combination of settings that will enable both in math mode?

**Comment by LordZorgoth** [comment]
Looking at the code, I'm baffled by the problem I'm having. It looks like company-latex-commands is supposed to ignore the values of the customizations I changed, so I don't know why it is loading in math mode under one setting and failing to load under another. Does company calling the math symbols backend preclude it checking with the latex commands backend for some reason?

**Comment by LordZorgoth** [comment]
Ah, I understand now. It is indeed the issue of multiple backends. There are two things one can do: the easiest is to bind a key to company-other-backtab to switch.

The other, which is not suitable for the project in general, is replace the company-math--symbols with (append math-symbol-list-latex-commands company-math--symbols) in the definition of company-math-symbols-latex. That's what I'm doing, because it's the most practical quick fix for someone who is writing LaTeX. I think that if we aren't getting group backends any time soon, there should be a custom variable to enable this, but for the reasons you noted it's not a solution.

While there is some reason to maintain the LaTeX math symbols list and backend as a separate entity, it should be noted that there should be two LaTeX command lists/backends. Most LaTeX commands work either only in math mode or only out of math mode.

The long-term solution would be to implement group backends that use the backends applicable to one's situation (specifically, you'll want a latex math mode backend that combines a math symbols and a math commands backend).

**Comment by vspinu** [comment]
> Long term, the code should make a distinction between LaTeX commands that only work in math mode, LaTeX commands that only work outside math mode, and LaTeX commands that work in both modes. 

This boils down to digging up those lists. Feel free to contribute these lists if you fill like.

> Actually, now I don't have completions for symbols. It seems like I can only have one or the other, which is of course rather suboptimal. 

That's company mode thing. If a completion is found in one backend furthermost backends won't be triggered. You can group backends to avoid that.

> I think that if we aren't getting group backends any time soon, there should be a custom variable to enable this, but for the reasons you noted it's not a solution.

Company allows grouped backends. You should do something like 

```
  (setq-local company-backends
              (append '((company-math-symbols-latex company-latex-commands))
                      company-backends))
```

See the docs of `company-backends`.

**Comment by LordZorgoth** [comment]
Thanks!

I'd suggest including something on grouped backends in the documentation of company-math. company-latex-commands simply being present seems to prevent company-math-symbols-unicode from ever being loaded for me, and grouping the backends solves that problem.

**Comment by vspinu** [comment]
> I'd suggest including something on grouped backends in the documentation of company-math

I did that but forgot to close this issue. Thanks for all the input!
